SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE hotelmanager.reservation;
DROP TABLE hotelmanager.role;
DROP TABLE hotelmanager.room;
DROP TABLE hotelmanager.service;
DROP TABLE hotelmanager.permission;
DROP TABLE hotelmanager.user;
DROP TABLE hotelmanager.service_request;
DROP TABLE hotelmanager.role_permission;
DROP TABLE hotelmanager.audit_log;
SET FOREIGN_KEY_CHECKS = 1;